name: Build release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build release
        run: |
          npm run build
          npm run pack
          ls
      - name: Upload release asset
        uses: actions/upload-artifact@v2
        with:
          name: Release package
          path: dist/
